export const environment = {
  apiEndpoint: 'http://localhost:8080/api',
  AllTrains: [
    {
      TrainNumber: '9003',
      TrainName: 'BDTS NZM RAJ SPL',
      Source: 'BANDRA TERMINUS',
      Departure: '16:05',
      Destination: 'H NIZAMUDDIN',
      Arrival: '06:00',
    },
    {
      TrainNumber: '9004',
      TrainName: 'NZM BDTS RAJ SPL',
      Source: 'H NIZAMUDDIN',
      Departure: '16:15',
      Destination: 'BANDRA TERMINUS',
      Arrival: '06:10',
    },
    {
      TrainNumber: '12235',
      TrainName: 'DBRG NDLS RAJEXP',
      Source: 'DIBRUGARH',
      Departure: '19:25',
      Destination: 'NEW DELHI',
      Arrival: '13:55',
    },
    {
      TrainNumber: '12236',
      TrainName: 'NDLS DBRG RJDHN',
      Source: 'NEW DELHI',
      Departure: '09:25',
      Destination: 'DIBRUGARH',
      Arrival: '05:15',
    },
    {
      TrainNumber: '12301',
      TrainName: 'KOLKATA RAJDHNI',
      Source: 'HOWRAH JN',
      Departure: '16:55',
      Destination: 'NEW DELHI',
      Arrival: '10:00',
    },
    {
      TrainNumber: '12302',
      TrainName: 'KOLKATA RJDHNI',
      Source: 'NEW DELHI',
      Departure: '16:55',
      Destination: 'HOWRAH JN',
      Arrival: '09:50',
    },
    {
      TrainNumber: '12305',
      TrainName: 'KOLKATA RJDHNI',
      Source: 'HOWRAH JN',
      Departure: '14:05',
      Destination: 'NEW DELHI',
      Arrival: '10:00',
    },
    {
      TrainNumber: '12306',
      TrainName: 'KOLKATA RJDHNI',
      Source: 'NEW DELHI',
      Departure: '16:55',
      Destination: 'HOWRAH JN',
      Arrival: '12:15',
    },
    {
      TrainNumber: '12309',
      TrainName: 'RJPB RAJDHANI',
      Source: 'RAJENDRANAGAR T',
      Departure: '19:00',
      Destination: 'NEW DELHI',
      Arrival: '07:40',
    },
    {
      TrainNumber: '12001',
      TrainName: 'NDLS SHATABDI',
      Source: 'HABIBGANJ',
      Departure: '15:00',
      Destination: 'NEW DELHI',
      Arrival: '23:30',
    },
    {
      TrainNumber: '12002',
      TrainName: 'BHOPAL SHTBDI',
      Source: 'NEW DELHI',
      Departure: '06:00',
      Destination: 'HABIBGANJ',
      Arrival: '14:25',
    },
    {
      TrainNumber: '12003',
      TrainName: 'LJN SWRAN SHTBD',
      Source: 'LUCKNOW NE',
      Departure: '15:35',
      Destination: 'NEW DELHI',
      Arrival: '22:15',
    },
    {
      TrainNumber: '12004',
      TrainName: 'LJN SWRAN SHTBD',
      Source: 'NEW DELHI',
      Departure: '06:10',
      Destination: 'LUCKNOW NE',
      Arrival: '12:40',
    },
    {
      TrainNumber: '12005',
      TrainName: 'KALKA SHTBDI',
      Source: 'NEW DELHI',
      Departure: '17:15',
      Destination: 'KALKA',
      Arrival: '21:20',
    },
    {
      TrainNumber: '12006',
      TrainName: 'KALKA SHTBDI',
      Source: 'KALKA',
      Departure: '06:15',
      Destination: 'NEW DELHI',
      Arrival: '10:20',
    },
  ],
  AllStations: [
    {
      stationID: 1,
      stationName: 'MADURAI JUNCTION',
      stationCode: 'MDU',
    },
    {
      stationID: 2,
      stationName: 'TIRCHCHIRAPPALLI JUNCTION',
      stationCode: 'TPJ',
    },
    {
      stationID: 5,
      stationName: 'SHIMOGA',
      stationCode: 'SME',
    },
    {
      stationID: 18,
      stationName: 'HUBLI',
      stationCode: 'UBL',
    },
    {
      stationID: 20,
      stationName: 'Solapur',
      stationCode: 'SLP',
    },
    {
      stationID: 79,
      stationName: 'BELGUAM',
      stationCode: 'BGM',
    },
  ],
};
